### ISSUE TITLE
Nix Derivation/Shell for quick setup

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/ogmios#1]
1. the existing ogmios derivation appears to be broken.
2. we need a quick way (modulo syncing) to get a testnet + chain index running - this may already exists, in which case just shoot the docs to @Benjmhart, can be nix, docker, etc.

this will facilitate `cardano-browser-tx` development while we add datum features

**Comment by Benjmhart** [comment]
![2021-12-16_14-08](https://user-images.githubusercontent.com/13956076/146433447-71b11c65-774b-4586-a9aa-8aaf9d61c105.png)

**Comment by ngua** [comment]
I'm going to try to take care of this today by fixing the flake.nix

**Comment by ngua** [comment]
For the second item, @mikekeke has a gist for setting up the hosted PAB scenario which includes how to get the testnet and chain index running: https://gist.github.com/mikekeke/883d56c38e0237444ac98ae5257e174f#gistcomment-3962799

**Comment by zygomeb** [comment]
closed by #2
