### ISSUE TITLE
Purescript client

### ISSUE THREAD

**Issue by ngua** [mlabs-haskell/ogmios#5]
Ogmios currently comes with a TypeScript client that communicates with the server via websockets. We might want to create a similar client in Purescript, which at a minimum should manage the websocket connection and drive the mini-protocols

**Comment by Benjmhart** [comment]
update: we have the initial wiring for cardano-browser-tx in raw websockets,   if generating a client is difficult OR if the client doesn't use `Aff` monad, i'd say this isn't worthwhile

the types can be reasonably understood by examining the typescript client source, and the websocket protocol is reasonable to navigate.
